# Generated by Django 6.0.1 on 2026-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostcodeDistrictData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode_district", models.CharField(max_length=10, unique=True)),
                ("price_2021", models.FloatField(null=True)),
                ("price_2022", models.FloatField(null=True)),
                ("price_2023", models.FloatField(null=True)),
                ("price_2024_predicted", models.FloatField(null=True)),
                ("change_2021_2022", models.FloatField(null=True)),
                ("change_2022_2023", models.FloatField(null=True)),
                ("change_2023_2024_predicted", models.FloatField(null=True)),
            ],
        ),
    ]
