# Generated by Django 6.0.1 on 2026-04-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecentPostcodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode_1",
                    models.CharField(
                        blank=True,
                        help_text="Most recent postcode",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "postcode_2",
                    models.CharField(
                        blank=True,
                        help_text="Second most recent postcode",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "postcode_3",
                    models.CharField(
                        blank=True,
                        help_text="Third most recent postcode",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_postcodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
