# Generated by Django 6.0.1 on 2026-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstock",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
