# Generated by Django 6.0.1 on 2026-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_userstock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
    ]
