# Generated by Django 6.0.1 on 2026-05-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userstock_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='currency',
        ),
    ]
