# Generated by Django 6.0.1 on 2026-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_userstock_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
    ]
